image: archlinux
secrets:
  - 820d708b-337f-4ab6-9a33-b9c4d1469b57
packages:
  - rustup
sources:
  - https://git.sr.ht/~tudor/rwsh
tasks:
  - setup: |
      rustup install stable
      rustup default stable
      export RUST_BACKTRACE=full
  - build: |
      cd rwsh
      cargo build --verbose
      cargo test --verbose
  - push_to_github: |
      cd rwsh
      git push --all "https://tudurom:$(cat ~/.gh_pass)@github.com/tudurom/rwsh"
