[package]
name = "rwsh"
version = "0.1.0"
authors = ["Tudor Roman <tudurom@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.13.0"
regex = "1.1.6"
dirs = "1.0.5"
clap = "2.33.0"
libc = "0.2.54"
rustyline = "4.0.0"
result = "1.0.0"
calculate = "0.5.1"
glob = "0.3.0"
bitflags = "1.1.0"
